apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: codeway-project
  namespace: argocd
spec:
  destination:
    namespace: argocd-project
    server: https://kubernetes.default.svc
  project: default
  source:
    path: node-deploy
    repoURL: https://github.com/BgMuhendis/argocd-project.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
      