apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dev
  template:
    metadata:
      name: dev-pod
      labels:
        app: dev
    
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq
  