apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.deployment.name}}
spec:
  replicas: 5
  selector:
    matchLabels:
      app: {{.Values.app.name}}
  template:
    metadata:
      labels:
        app: {{.Values.app.name}}
    
    spec:
      containers:
        - name: node-app
          image: muhammethadikamat/{{.Values.deployment.image}}
          ports:
            - containerPort: 3000
          env:
            - name: NAME
              value: Hadi
  