apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.app.name}}
spec:
  replicas: 5
  selector:
    matchLabels:
      app: {{.Values.app.name}}
  template:
    metadata:
      labels:
        app: {{.Values.app.name}}
    
    spec:
      containers:
        - name: nginx
          image: muhammethadikamat/{{.Values.image.name}}
          ports:
            - containerPort: 3000
          env:
            - name: NAME
              value: "Muhammet"
  