apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30080
  selector:
    app: {{.Values.app.name}}